#!/bin/bash

OSMAND_APPNAME="OsmAnd~"
OSMAND_VERSION="1.9.4"
OSMAND_VERCODE="194"
OSMAND_SUBDIR="android/OsmAnd"

err() {
	echo ERROR: "$@"
	exit 1
}

# Uses ANDROID_SDK instead of ANDROID_HOME
if [[ -z $ANDROID_SDK ]] && [[ -n $ANDROID_HOME ]]
then
	export ANDROID_SDK="$ANDROID_HOME"
fi

if [[ -d $OSMAND_SUBDIR ]]
then
	cd $OSMAND_SUBDIR || err "Could not enter android/OsmAnd subdirectory"
fi

# Replace the name given to the full paid app
sed -i "s/\"OsmAnd+\"/\"$OSMAND_APPNAME\"/g" build.xml || err "Could not replace application name"

# Build native code
./old-ndk-build.sh || err "Failed to build native code"

# Build the rest
ant \
	-Dsdk.dir="$ANDROID_SDK" \
	-Dndk.dir="$ANDROID_NDK" \
	-DBLACKBERRY_BUILD=false \
	-DBUILD_SUFFIX= \
	-Dbuild.version="$OSMAND_VERSION" \
	-DAPK_VERSION="$OSMAND_VERSION" \
	-Dbuild.version.code="$OSMAND_VERCODE" \
	-DAPK_NUMBER_VERSION="$OSMAND_VERCODE" \
	"-DFEATURES=+play_market +gps_status -parking_plugin -blackberry -amazon -route_nav" \
	-DCLEAN_CPP=false \
	-DPACKAGE_TO_BUILT=net.osmand.plus \
	-Dnet.osmand.plus= \
	-Dnativeoff=false \
	"-DversionFeatures=+play_market +gps_status -parking_plugin -blackberry -amazon -route_nav" \
	clean release || err "Failed to build OsmAnd (java) via ant"
