#!/bin/sh

OSMAND_APPNAME="OsmAnd~"
OSMAND_VERSION="2.0.3"
OSMAND_VERCODE="205"
OSMAND_SUBDIR="android/OsmAnd"

# '+' enables, '-' disables
# As found in upstream's jenkins log
# OSMAND_FEATURES="-play_market -gps_status -parking_plugin -blackberry +amazon -route_nav"
# Our slightly modified version
OSMAND_FEATURES="-play_market +gps_status -parking_plugin -blackberry -amazon -route_nav"

err() {
	echo ERROR: "$@"
	exit 1
}

if [ -d $OSMAND_SUBDIR ]
then
	cd $OSMAND_SUBDIR || err "Could not enter $OSMAND_SUBBDIR subdirectory"
fi

# Build native code
./old-ndk-build.sh || err "Failed to build native code"

TARGET_APP_NAME="$OSMAND_APPNAME"
APP_NAME="$OSMAND_APPNAME"
APP_FEATURES="$OSMAND_FEATURES"
APK_NUMBER_VERSION="$OSMAND_VERCODE"
APK_VERSION="$OSMAND_VERSION"

sed -e '/qt.*Compile/d' -i build.gradle
sed -e '/signingConfig\s\+signingConfigs\./d' -i build.gradle

sed -i -e '/sourceSets/icompileOptions {\nsourceCompatibility = JavaVersion.VERSION_1_7\ntargetCompatibility = JavaVersion.VERSION_1_7\n}\n\n' ../eclipse-compile/appcompat/build.gradle build.gradle

sed -i -e "s/System.getenv(\"APK_VERSION\")/\"${APK_VERSION}\"/g" build.gradle
sed -i -e "s/System.getenv(\"APK_NUMBER_VERSION\")/\"${APK_NUMBER_VERSION}\"/g" build.gradle
sed -i -e "s/System.getenv(\"APP_FEATURES\")/\"${APP_FEATURES}\"/g" build.gradle
sed -i -e "s/System.getenv(\"APP_NAME\")/\"${APP_NAME}\"/g" build.gradle
sed -i -e "s/System.getenv(\"TARGET_APP_NAME\")/\"${APP_NAME}\"/g" build.gradle
